### ISSUE TITLE
Changing the All Variants Give Rewards option to false causes Risk of Rain 2 to hang at startup/Disabling arrival announcements doesn't seem to do anything

### ISSUE THREAD

**Issue by whitedude877** [Nebby1999/VarianceAPI#6] opened 2021-09-16 23:27 UTC
Changing disable arrival announcements to true still yields arrival announcements for variant enemies.

**Comment by Nebby1999** [comment] 2021-10-22 23:47
The game hanging at startup was caused by a log message trying to get the type of something that didnt exist, hanging the game. this will be fixed on the next release

The other was far simpler and simply was a missing if check.

**Closed as completed by Nebby1999** 2021-10-22 23:47 UTC
